name: dez
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.5517074239905924
title: Dez Futak
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1875
  lightness: 0.3874835129827261
  saturation: 0.26688240352086723
  rhythmicContrast: 0.7901814675424248
purpose: []
